from pydantic import BaseModel
from typing import Optional, List
from pydantic import BaseModel, Field
from bson import ObjectId
from typing_extensions import Annotated
from pydantic.functional_validators import BeforeValidator
from .garments import Garment


PyObjectId = Annotated[str, BeforeValidator(str)]

class UserBase(BaseModel):
    # generated by FastAPI
    id: Optional[str] = None
    joinedDate: Optional[str] = None

    # Optional fields
    imageBase64: Optional[str] = None
    description: Optional[str] = None
    
    # Required fields
    name: str

    # garments
    garments: Optional[List[Garment]] = []


# Custom Pydantic model to handle ObjectId serialization
# not sure if still needed
#     class Config:   
#         # Add a custom encoder for ObjectId to be converted into a string
#         json_encoders = {
#             ObjectId: str  # Converts ObjectId to a string
#         }


class UserCreate(UserBase):
    token: str  # Add token field to response



class UserUpdate(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    imageBase64: Optional[str] = None
    garments: Optional[List[Garment]] = []


class UserResponse(UserBase):
    pass