version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: fastapi-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    ports:
      - "27017:27017"
  fastapi:
    build: .
    container_name: fastapi-server
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://admin:adminpass@mongo:27017"